### ISSUE TITLE
Support Django 4.x 

### ISSUE THREAD

**Issue by GabrielBlondeau-Kirby** [koladev32/drf-apikey#41]
Hey guys,

I'm migrating my system from Django 3.2 to the version 4.2 (rc1).

I was using the lib `djangorestframework-api-key` in order to manage my API Keys. But it does not support Django 4+...

So I found your lib and I was wondering if it does support Django 4.1 or even more (4.2, etc) ?

Have a nice day!

**Comment by koladev32** [comment]
Hey @GabrielBlondeau-Kirby 

We are currently supporting `Django 4.1`. 

Do you have some issues integrating the package with `Django 4.1`? Please, tell us what are the issues.
